#!/usr/bin/env ruby
require 'taptag'
require 'taptag/nfc'
require 'drb/drb'
require 'fileutils'
require 'daemons'

ACTIONS = %w[start stop pid active].freeze
PID_FOLDER = "/run/user/#{`id`.split(/\s+/).map { |s| s.scan(/(\w+)/) }.flatten[1]}".freeze
DRB_URI = ENV['DRB_URI'] || 'druby://0.0.0.0:8787'

dameon_args = {
  app_name: 'taptagd',
  dir_mode: :normal,
  dir: PID_FOLDER,
  multiple: false
}

Daemons.run_proc('taptagd', dameon_args) do
  DRb.start_service(DRB_URI, Taptag::NFC)
  DRb.thread.join
end
